service: moonrides

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  environment:
    TRIPS_TABLE: TripsTable
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:Query
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TRIPS_TABLE}

functions:
  # Lambda to login recent trips
  login:
    image: moonrides-image
    events:
      - http:
          path: login
          method: post
  
  # Lambda for getting recent trips
  getRecentTrips:
    image: moonrides-image
    events:
      - http:
          path: trips
          method: get

  # Lambda for selecting a ride
  requestRide:
    image: moonrides-image
    events:
      - http:
          path: request
          method: post

  # Lambda for processing payment
  processPayment:
    image: moonrides-image
    events:
      - http:
          path: payment
          method: post

resources:
  Resources:
    RecentTripsTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${self:provider.environment.TRIPS_TABLE}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: tripDate
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: tripDate
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    layer: true
    slim: true
    zip: true

package:
  individually: true
  exclude:
    - node_modules/**
    - .serverless/**
    - .webpack/**
    - .pytest_cache/** # Exclude pytest cache if present
    - tests/** # Exclude tests directory if present
