name: Deploy Moonride Backend

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Clean and install Node.js dependencies
        run: |
          rm -rf node_modules
          npm ci
          npm install -g serverless
          npm install -g serverless-python-requirements

      - name: Set up Python and install dependencies
        run: |
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip
          python -m venv lambdas/venv
          source lambdas/venv/bin/activate
          pip install --no-cache-dir -r lambdas/requirements.txt
          find lambdas/venv/lib/python*/site-packages -type d -name '__pycache__' -exec rm -rf {} +
          find lambdas/venv/lib/python*/site-packages -type d -name '*.dist-info' -exec rm -rf {} +

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Moonrides Backend
        working-directory: ./lambdas
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        run: serverless deploy --verbose
